name: k_airways_flutter
description: A frontend Flutter project for Kenya airways project.
publish_to: 'none' # Remove this line if you plan to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^8.0.0
  intl: ^0.20.2
  fluttertoast: ^8.2.4
  latlong2: ^0.8.1
  flutter_svg: ^2.0.7
  shimmer: ^3.0.0
  animations: ^2.0.7
  google_fonts: ^4.0.4
  liquid_swipe: ^3.1.0
  cached_network_image: ^3.3.0
  go_router: ^15.2.3
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.66.0
  dio: ^5.8.0+1
  json_annotation: ^4.8.1
  kenya_airways_flutter_sdk:
    path: ./kenya_airways_flutter_sdk
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  built_value_generator: ^8.9.0

flutter:
  uses-material-design: true
  generate: true

